# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: discordo
version: 2
env:
  - CGO_ENABLED=1

builds:
  - id: discordo-win
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++

  - id: discordo-linux
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++

  - id: discordo-darwin-amd64
    goos: [darwin]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++

  - id: discordo-darwin-arm64
    goos: [darwin]
    goarch: [arm64]
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++

archives:
  - format: binary
    name_template: >-
      discordo_
      {{- if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}

before:
  hooks:
    - go mod tidy
