# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: discordo
builds:
  - env: [CGO_ENABLED=1]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
release:
  prerelease: "true"
