# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# NOTE: if this is not here LSPs will complain about missing version
# (only relevant for goreleaser, does not impact actual version tags)
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"

archives:
  - formats: ["zip", "tar.gz"]
