
# Global shortcuts
# Esc: Reset message selection or close the channel selection popup.
[keybinds]
focus_guilds_tree = "ctrl+g"
focus_messages_list = "ctrl+t"
focus_message_input = "ctrl+i"
# Cycle focus between the widgets.
focus_previous = "ctrl+h"
focus_next = "ctrl+l"
# Hide/show the guilds tree.
toggle_guilds_tree = "ctrl+b"
quit = "ctrl+c"
# Log out and remove the authentication token from keyring.
# Requires re-login upon restart.
logout = "ctrl+d"

[keybinds.picker]
toggle = "ctrl+k"
cancel = "esc"
up = "ctrl+p"
down = "ctrl+n"
top = "home"
bottom = "end"
select = "enter"

# Only while focusing on the guilds tree
[keybinds.guilds_tree]
up = "k"
down = "j"
top = "g"
bottom = "G"
# Select the currently highlighted text-based channel or expand a guild or channel.
select_current = "enter"
yank_id = "i"
collapse_parent_node = "-"
move_to_parent_node = "p"

# Only while focusing on sent messages
[keybinds.messages_list]
select_up = "k"
select_down = "j"
select_top = "g"
select_bottom = "G"
# Scroll the messages list without changing the selection.
scroll_up = "K"
scroll_down = "J"
scroll_top = "home"
scroll_bottom = "end"
# Select the message reference (reply) of the selected channel.
select_reply = "s"
# Reply to the selected message.
reply = "R"
# Reply (with mention) to the selected message.
reply_mention = "r"
cancel = "esc"
edit = "e"
delete = "D"
delete_confirm = "d"
# Open the selected message's attachments or hyperlinks in the message
# using the default browser application.
open = "o"
# Yank (copy) the selected message's content/url/id.
yank_content = "y"
yank_url = "u"
yank_id = "i"

# Only while typing a message
# Alt+Enter: Insert a new line to the current text.
[keybinds.message_input]
# paste from clipboard (supports both text and images)
paste = "ctrl+v"
send = "enter"
# Remove existing text or cancel reply.
cancel = "esc"
# Complete usernames when mentioning
tab_complete = "tab"

open_editor = "ctrl+e"
open_file_picker = "ctrl+\\"

[keybinds.mentions_list]
up = "ctrl+p"
down = "ctrl+n"
top = "home"
bottom = "end"
