# Whether the mouse is usable or not.
mouse: true

# Whether to draw the timestamps of the corresponding message in front of it.
timestamps: false
# Whether to draw the timestamps before the name of author of the message or not.
timestamps_before_author: false

# The number of messages to fetch when a text-based channel is selected. The value must be >0 and <=100.
messages_limit: 50

# The name of the program to launch when the launch_editor key is pressed. If the value of the field is set to "default", the `$EDITOR` environment variable is used instead.
editor: default

keys:
  normal:
    Rune[i]: insert_mode

    Ctrl+G: focus_guilds_tree
    Ctrl+T: focus_messages_text
    Ctrl+P: focus_message_input

    Rune[j]: select_down
    Rune[k]: select_up

    Rune[b]: toggle_guilds_tree

    messages_text:
      Rune[c]: copy
      Rune[d]: delete

      Rune[J]: select_next
      Rune[K]: select_prev

      Rune[r]: reply
      Rune[R]: reply_mention

      Rune[s]: select_reply

    message_input:
      Rune[e]: launch_editor

  insert:
    Esc: normal_mode

    message_input:
      Enter: send

theme:
  border: true
  border_color: default
  border_padding: [0, 0, 1, 1]

  title_color: default
  background_color: default

  guilds_tree:
    graphics: true

  messages_text:
    author_color: aqua
    reply_indicator: ╭
