on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: release publish
        run: |
          docker run \
          --rm \
          -e 'GITHUB_TOKEN${{secrets.GITHUB_TOKEN}}' \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v `pwd`:/go/src/github.com/ayn2op/discordo \
          -w /go/src/github.com/ayn2op/discordo \
          ghcr.io/goreleaser-cross:latest \
          release --clean
